import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author juanjose
 */
public class AgendaGUIForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Agenda
     */
    public AgendaGUIForm() {
        initComponents();
    }
    
    public AgendaGUIForm(Controlador controlador){
        initComponents();
        this.controlador = controlador;
        this.contenidoListaNombres = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPersonas = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        menuGuardarComo = new javax.swing.JMenuItem();
        menuImprimir = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuOrdenar = new javax.swing.JMenu();
        menuOrdenarNombre = new javax.swing.JMenuItem();
        menuOrdenarCP = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenu();
        menuItemBuscar = new javax.swing.JMenuItem();
        menuItemBuscarDeNuevo = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaPersonas.setModel(this.contenidoListaNombres);
        jScrollPane1.setViewportView(listaPersonas);

        btnAgregar.setText("Agregar");
        btnAgregar.setPreferredSize(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setPreferredSize(null);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        menuArchivo.setText("Archivo");

        menuNuevo.setLabel("Nuevo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuNuevo);

        menuAbrir.setLabel("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuAbrir);

        Guardar.setLabel("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(Guardar);

        menuGuardarComo.setLabel("Guardar como...");
        menuGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarComoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuGuardarComo);

        menuImprimir.setText("Imprimir");
        menuImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImprimirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuImprimir);

        menuSalir.setLabel("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSalir);

        menuBar.add(menuArchivo);

        menuOrdenar.setText("Ordenar");

        menuOrdenarNombre.setLabel("Por nombre");
        menuOrdenar.add(menuOrdenarNombre);

        menuOrdenarCP.setLabel("Por C.P.");
        menuOrdenar.add(menuOrdenarCP);

        menuBar.add(menuOrdenar);

        menuBuscar.setText("Buscar");

        menuItemBuscar.setText("Buscar");
        menuBuscar.add(menuItemBuscar);

        menuItemBuscarDeNuevo.setText("Buscar de nuevo");
        menuBuscar.add(menuItemBuscarDeNuevo);

        menuBar.add(menuBuscar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        this.controlador.agregar();
    }                                          

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.controlador.editar((String)this.listaPersonas.getSelectedValue());
    }                                         

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String nombrePersona = (String)this.listaPersonas.getSelectedValue();
        this.controlador.eliminar(nombrePersona);
    }                                           

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.controlador.nuevo();
    }                                         

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.controlador.abrir();
    }                                         

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        this.controlador.guardar();
    }                                       

    private void menuGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        this.controlador.guardarComo();
    }                                               

    private void menuImprimirActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        this.controlador.imprimir();
    }                                            

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        this.controlador.salir();
    }                                         

    public Agenda getAgenda(){
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda){
        this.agenda = agenda;
        this.agenda.addObserver(this);
        update(this.agenda, null);
    }
    
    public void mostrarError(String mensaje){}
    
    public void busquedaEncontrada(int indice){}
    
    @Override
    public void update(Observable observable, Object obj){
        if(observable == this.agenda){
            int indiceActual = this.listaPersonas.getSelectedIndex();
            this.contenidoListaNombres.removeAllElements();
            String[] nombres = this.agenda.getNombres();
            for (String nombre : nombres) {
                this.contenidoListaNombres.addElement(nombre);
            }
            if(indiceActual >= 0)
                this.listaPersonas.ensureIndexIsVisible(indiceActual);
            else
                this.listaPersonas.ensureIndexIsVisible(this.contenidoListaNombres.getSize()-1);
            
            SwingUtilities.invokeLater(() -> {
                actualizar();
            });
            
            setTitle(this.agenda.getTitulo());
        }
    }
    
    private void actualizar(){
         this.listaPersonas.repaint();
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgendaGUIForm(new Controlador(new SistemaDeArchivos())).setVisible(true);
        });
    }
    
    
    /**
     * variables de instancia
     */
    private Controlador controlador;
    private Agenda agenda;
    private DefaultListModel contenidoListaNombres;
    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPersonas;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBuscar;
    private javax.swing.JMenuItem menuGuardarComo;
    private javax.swing.JMenuItem menuImprimir;
    private javax.swing.JMenuItem menuItemBuscar;
    private javax.swing.JMenuItem menuItemBuscarDeNuevo;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenu menuOrdenar;
    private javax.swing.JMenuItem menuOrdenarCP;
    private javax.swing.JMenuItem menuOrdenarNombre;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration                   

}
